### ISSUE TITLE
apply version tags and releases

### ISSUE THREAD

**Issue by prjemian** [JZTischler/srange#4]
Since there are no [tags](https://github.com/JZTischler/srange/tags) or [releases](https://github.com/JZTischler/srange/releases) yet on this repository, packaging will get stuck on this step.

[Packaging](#1) relies on version numbers.  A common practice is to use the GitHub repository tags.  I suggest this repository adopt the [semantic versioning](https://semver.org) strategy.  The [python versioneer](https://github.com/warner/python-versioneer) project is used by many python packages to assist when building the packages for publishing.  Versioneer reads the current tag from the repository and builds that into the name of the package.

There is a long interval in the repository commit history between 2014 and this month.  I suggest that we tag the last commit in 2014 (caff338) as `1.0.0`.  Applying *semver* principles, the recent commit does not break the 1.0.0 interface, but rather adds new capability (use with Python 3 AND still use with python 2.7).  This is a *minor* change, according to *semver*.  I suggest that we are working on tag `1.1.0`.

**Comment by prjemian** [comment]
see https://github.com/JZTischler/srange/releases/tag/1.0.0

**Comment by prjemian** [comment]
actually:

* 1.1.0 [release](https://github.com/JZTischler/srange/releases/tag/1.1.0) (9e9b292) adds Python 3
* 1.1.1 [release milestone](https://github.com/JZTischler/srange/milestone/1) will add packaging for PyPI and conda

**Comment by JZTischler** [comment]
Pete,
Any versioning is OK with me.
Really, just pick one and I will extol it as is a perfect choice.
Jon
